### ISSUE TITLE
improve performences

### ISSUE THREAD

**Issue by jpheos** [JYMathieu69/carotte_ta_coloc#153]
https://github.com/JYMathieu69/carotte_ta_coloc/blob/041f0e41d8d50c10d80a85199cb6f8f76cd2c6f7/app/controllers/coloc_tasks_controller.rb#L6-L7

Improve performence with:
```ruby
    @addable_tasks = Task.where.not(id: @coloc.coloc_tasks.select(:id))
```

**Comment by fannymugnier** [comment]
Thank you for pointing it out :)
